---
# tasks file for common

- name: Set timezone to CET
  file: 
    src: /usr/share/zoneinfo/Europe/Amsterdam
    dest: /etc/localtime
    state: link
  when: ansible_distribution=="CentOS"

- name: Install required packages
  yum:
    name: "{{ required_packages }}"
    state: installed


- name: set aws cli region
  command: aws configure set region {{ aws_region }}
  become: true
  become_user: "{{ item }}"
  with_items: 
    - root
    - ec2-user



