---
# tasks file for consul_base

- name: create consul install directory
  file:
    path: "{{ consul_install_dir }}"
    state: directory
    owner: root
    group: root

- name: unpack consul on machine
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: "{{ consul_install_dir }}"
    creates: "{{ consul_install_dir }}/consul"
    remote_src: yes 
    owner: root
    group: root

- name: Install link to consul in /usr/local/bin
  file:
    src: "{{ consul_install_dir }}/consul"
    dest: /usr/local/bin/consul
    state: link

- name: Setup configuration directory
  file:
    state: directory
    path: "{{ consul_config_dir }}"
    owner: root
    group: root

- name: Setup data directory
  file:
    state: directory
    path: "{{ consul_data_dir }}"
    owner: root
    group: root

- name: Setup systemd service definition
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root

- name: Create consul service
  service:
    name: consul
    enabled: yes
